OPPONENT_TYPE_UNKNOWN = "unknown"
OPPONENT_TYPE_TIGHT = "tight"
OPPONENT_TYPE_AGGRESSIVE = "aggressive"
OPPONENT_TYPE_CALLING = "calling"
OPPONENT_TYPE_OTHER = "other"

TRAINING_OPPONENT_TYPES = (
    OPPONENT_TYPE_TIGHT,
    OPPONENT_TYPE_AGGRESSIVE,
    OPPONENT_TYPE_CALLING,
)

POLICY_TYPES = (
    OPPONENT_TYPE_UNKNOWN,
    OPPONENT_TYPE_TIGHT,
    OPPONENT_TYPE_AGGRESSIVE,
    OPPONENT_TYPE_CALLING,
)

STATE_ENCODER_OPPONENT_TYPE_IDS = {
    OPPONENT_TYPE_UNKNOWN: 0,
    OPPONENT_TYPE_AGGRESSIVE: 1,
    OPPONENT_TYPE_TIGHT: 2,
    OPPONENT_TYPE_OTHER: 3,
    OPPONENT_TYPE_CALLING: 4,
}
