OPPONENT_TYPE_UNKNOWN = "unknown"
OPPONENT_TYPE_TIGHT = "tight"
OPPONENT_TYPE_AGGRESSIVE = "aggressive"
OPPONENT_TYPE_CALLING = "calling"
OPPONENT_TYPE_OTHER = "other"

TRAINING_OPPONENT_TYPES = (
    OPPONENT_TYPE_TIGHT,
    OPPONENT_TYPE_AGGRESSIVE,
    OPPONENT_TYPE_CALLING,
)

POLICY_TYPES = (
    OPPONENT_TYPE_UNKNOWN,
    OPPONENT_TYPE_TIGHT,
    OPPONENT_TYPE_AGGRESSIVE,
    OPPONENT_TYPE_CALLING,
)
