EPSILON_SCHEDULE_LINEAR = "linear"
EPSILON_SCHEDULE_EXPONENTIAL = "exponential"

SUPPORTED_EPSILON_SCHEDULES = (
    EPSILON_SCHEDULE_LINEAR,
    EPSILON_SCHEDULE_EXPONENTIAL,
)

ALPHA_MODE_CONSTANT = "constant"
ALPHA_MODE_VISIT_COUNT = "visit_count"
ALPHA_MODE_SQRT_VISIT = "sqrt_visit"

MODEL_TYPE_GENERAL_POLICY = "general_policy"
MODEL_TYPE_SPECIALIST = "specialist"

SUPPORTED_ALPHA_MODES = (
    ALPHA_MODE_CONSTANT,
    ALPHA_MODE_VISIT_COUNT,
    ALPHA_MODE_SQRT_VISIT,
)
