from src.poker.constants import (
    OPPONENT_TYPE_AGGRESSIVE,
    OPPONENT_TYPE_CALLING,
    OPPONENT_TYPE_TIGHT,
)

PLAYER_NAME_ADAPTIVE_MC = "adaptive_mc"
PLAYER_NAME_FIXED_POLICY = "fixed_policy"
PLAYER_NAME_ORACLE_MC = "oracle_mc"
PLAYER_NAME_GENERAL_POLICY = "general_policy"
PLAYER_NAME_POLICY_GENERAL_MC = "policy_general_mc"
PLAYER_NAME_SPECIALIST_MC = "specialist_mc"
PLAYER_NAME_ALWAYS_RAISE = "always_raise"
PLAYER_NAME_ALWAYS_CALL = "always_call"

OPPONENT_CALLING_EXTREME = "calling_extreme"
OPPONENT_AGGRESSIVE_EXTREME = "aggressive_extreme"
OPPONENT_TIGHT_EXTREME = "tight_extreme"

GENERALIZATION_OPPONENTS = (
    OPPONENT_CALLING_EXTREME,
    OPPONENT_AGGRESSIVE_EXTREME,
    OPPONENT_TIGHT_EXTREME,
)

GENERALIZATION_OPPONENT_TO_BASE_TYPE = {
    OPPONENT_CALLING_EXTREME: OPPONENT_TYPE_CALLING,
    OPPONENT_AGGRESSIVE_EXTREME: OPPONENT_TYPE_AGGRESSIVE,
    OPPONENT_TIGHT_EXTREME: OPPONENT_TYPE_TIGHT,
}

GENERALIZATION_OPPONENT_SEEN_IN_TRAINING = {
    OPPONENT_CALLING_EXTREME: False,
    OPPONENT_AGGRESSIVE_EXTREME: False,
    OPPONENT_TIGHT_EXTREME: False,
}
