PLAYER_NAME_ADAPTIVE_MC = "adaptive_mc"
PLAYER_NAME_FIXED_POLICY = "fixed_policy"
PLAYER_NAME_ORACLE_ADAPTIVE = "oracle_adaptive"
PLAYER_NAME_SINGLE_POLICY = "single_policy"
PLAYER_NAME_SINGLE_POLICY_MC = "single_policy_mc"
PLAYER_NAME_SPECIALIST_MC = "specialist_mc"
PLAYER_NAME_ALWAYS_RAISE = "always_raise"

OPPONENT_VARIANT_CALLING_WEAK = "calling_weak"
OPPONENT_VARIANT_CALLING_MEDIUM = "calling_medium"
OPPONENT_VARIANT_CALLING_STRONG = "calling_strong"
OPPONENT_VARIANT_AGGRESSIVE_LIGHT = "aggressive_light"
OPPONENT_VARIANT_AGGRESSIVE_EXTREME = "aggressive_extreme"

CALLING_OPPONENT_VARIANTS = (
    OPPONENT_VARIANT_CALLING_WEAK,
    OPPONENT_VARIANT_CALLING_MEDIUM,
    OPPONENT_VARIANT_CALLING_STRONG,
)

AGGRESSIVE_OPPONENT_VARIANTS = (
    OPPONENT_VARIANT_AGGRESSIVE_LIGHT,
    OPPONENT_VARIANT_AGGRESSIVE_EXTREME,
)

GENERALIZATION_OPPONENT_VARIANTS = (
    *CALLING_OPPONENT_VARIANTS,
    *AGGRESSIVE_OPPONENT_VARIANTS,
)
