PLAYER_NAME_ADAPTIVE_MC = "adaptive_mc"
PLAYER_NAME_FIXED_POLICY = "fixed_policy"
PLAYER_NAME_ORACLE_MC = "oracle_mc"
PLAYER_NAME_GENERAL_POLICY = "general_policy"
PLAYER_NAME_POLICY_GENERAL_MC = "policy_general_mc"
PLAYER_NAME_SPECIALIST_MC = "specialist_mc"
PLAYER_NAME_ALWAYS_RAISE = "always_raise"
PLAYER_NAME_ALWAYS_CALL = "always_call"

OPPONENT_CALLING_EXTREME = "calling_extreme"
OPPONENT_AGGRESSIVE_EXTREME = "aggressive_extreme"
OPPONENT_TIGHT_EXTREME = "tight_extreme"

CALLING_GENERALIZATION_OPPONENTS = (
    OPPONENT_CALLING_EXTREME,
)

AGGRESSIVE_GENERALIZATION_OPPONENTS = (
    OPPONENT_AGGRESSIVE_EXTREME,
)

TIGHT_GENERALIZATION_OPPONENTS = (
    OPPONENT_TIGHT_EXTREME,
)

GENERALIZATION_OPPONENTS = (
    *CALLING_GENERALIZATION_OPPONENTS,
    *AGGRESSIVE_GENERALIZATION_OPPONENTS,
    *TIGHT_GENERALIZATION_OPPONENTS,
)
